version = 0.1
[default.deploy.parameters]
stack_name = "northernlion-api-production"
s3_bucket = "northernlion-sam-templates-production"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
